# Generated by Django 5.2.6 on 2025-10-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
