# Generated by Django 5.2.6 on 2025-10-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categroy', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=20)),
            ],
        ),
    ]
