# Generated by Django 5.2.6 on 2025-10-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('attendence', models.IntegerField()),
                ('internal_marks', models.IntegerField()),
                ('external_mark', models.IntegerField()),
                ('total_mark', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
